version: "3.7"
services:
  urt:
    image: ich777/urbanterror

    environment:
      START_PARAMS: ""
      CHECK_FOR_UPDATES: ""
      POSTGRES_DB: postgres
      UID: 1000
      GID: 1000
    ports:
      - "27960:27960/udp"
    volumes:
      - ./urban-terror:/urbanterror
  spunky:
    image: juanitomint/spunkybot:1.14.2
    volumes:
      - ./urban-terror/q3ut4:/opt/urbanterror/.q3a/q3ut4
      - ./conf/settings-docker.conf:/usr/src/app/conf/settings.conf
      - ./data.sqlite:/usr/src/app/data.sqlite
    depends_on:
      - urt